### ISSUE TITLE
Build endpoint request GUI

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#1]
## User story
As a developer testing mircoservice endpoints, I should be able to define data sources and destinations in a GUI, so that I can quickly test different endpoints depending on whichever test step I’m on.

### Acceptance criteria
- [x] Should have ability to enter a valid URI
- [x] Should have a way to submit HTTP request
- [x] Should have a way to choose `PUT`, `POST`, or `PATCH` methods in the _destination_ panel
- [x] Should default to `GET` method in the _source_ panel
- [x] Should be reusable in different panels

### Sub-tasks
- [x] Mock up design
- [x] Determine need for supporting non-GET requests
**⤷ For now, we’ll only support `GET` requests in the source panel, but support `PUT`, `POST`, and `PATCH` in the destination panel**
- [x] Build UI for entering API endpoint

**Comment by conor-jh** [comment]
Hey @joepav, I think we can use this issue for the “data request bar” (although it originally referred to  the whole data source panel). I’ve updated the description to reflect that.
