### ISSUE TITLE
Mock up front-end design

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#11]
## User story
As a developer working on this project, I should be able to reference UI mockups so that I have a clear vision to work toward and can separate development concerns from UX tasks.

### Sub-tasks
- [x] Research existing tools’ UI for inspiration and direction
- [x] Mock up relevant screens and basic user flow
- [ ] ~Export assets as needed for specific components~

**Comment by conor-jh** [comment]
Marking this as closed with the understanding that for MVP, we can narrow scope to the low-fidelity mockup Joel created from our whiteboard session. I think as we move beyond MVP we can take time to create higher-fidelity mockups and decide on a look and feel together. 

#### Mockup
[Frontend mock-up -2.pdf](https://github.com/oslabs-beta/apimocking/files/3258912/Frontend.mock-up.-2.pdf)
