### ISSUE TITLE
Set up and share environment

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#14]
Figure out as a team how to get our dev environment set up for productive coding:

- [x] Decide if we’re going to use Electron
**⤷ Yes**
- [x] Complete #13 (TypeScript usage)
- [x] Set up Webpack, Babel (if needed)
- [x] Decide on linting and formatting guidelines
**⤷ Slightly extended Airbnb styles, no separate formatter**
- [x] Set up basic file structure and initialize React app

**Comment by conor-jh** [comment]
Heads up—I modified the sub-task list to reflect decisions we’ve made so far and to add the task of setting up our directory structure and React app.
