### ISSUE TITLE
Data presentation

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#2]
## User story
As a developer, I should be able to see/read data shared between microservices so that I can better understand its shape for decision-making and testing purposes. 

### Acceptance criteria
- [x] Data should display on the screen
- [x] Data should display as a well-formatted JavaScript object
- [x] Data displayed on screen should match raw data from HTTP request (or imported file)
- [x] Should be able to render large datasets (>1000 lines)
- [x] Should be able to expand and collapse compound data structures (nested objects, arrays)

### Sub-tasks
- [x] Create UI mockups
- [x] Research tools to implement visualization (#15)
