### ISSUE TITLE
Provide authentication options

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#28]
## User story
As a developer testing microservices, I should be able to provide authentication credentials in my HTTP requests so that I can work with secure endpoints

### Sub-tasks
- [x] Research microservice authentication best practices
- [ ] ~Find solution for storing session information (look into SSO, cookies with Electron, etc.)~ (see #49)
- [x] Determine which authentication methods to support for MVP

### Acceptance criteria
📚 More research needed—will update
