### ISSUE TITLE
Manipulate data

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#3]
## User story
As a developer testing micro-service connections, I should be able to modify API data before it gets sent to its destination, so that I can test edge cases that may be difficult to come by naturally.

### Sub-tasks
- [x] Determine available modifications
⤷ All those supported by `react-json-view`: add, delete, edit value
- [x] ~Mock up UI for data manipulations~
- [x] ~Write unit tests to ensure modifications persist~

## Notes
* This issue is closely linked to how we present API data (#2), how we “save” tests, and how we send data to the destination micro-service
* Let’s think carefully about what data modifications make the most sense to support—we don’t necessarily _need_ to support arbitrary changes and it may make for a better UX to constrain modifications to the most common edge case scenarios

**Comment by conor-jh** [comment]
`react-son-view` takes care of most of this for us. Closing for now, but as we discussed we may need to revisit this issue as we build out support for non-JSON data formats
