### ISSUE TITLE
Mockup names/ids

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#33]
## User story
As a developer testing microservices, I should be able to distinguish mockups with a name, change summary, etc. so that I can understand which mockups I’m testing.

### Sub-tasks
- [x] Mock up UI for displaying mockups
- [x] Add ability to name mockups and/or show diff. summary

**Comment by conor-jh** [comment]
Here’s a basic mockup of how this might look for display:

![Test](https://user-images.githubusercontent.com/31315610/59553737-632fef00-8f67-11e9-8f97-c3912b1ba146.png)

### Acceptance criteria

- [x] Should be able to name individual mockups
- [x] Name should display in “Test” panel
- [x] Should be able to edit name in mockups panel
- [x] Name should be tied to unique mockup ID

### Not included in scope
- Ability to write assertions for tests (e.g. “Should result in 400 error”) (#52)
- Source/change diff (we currently show change as JSON, but it looks a little off if the change is a deletion or insertion) (#59)
