### ISSUE TITLE
Automatically test for common edge cases

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#4]
## User story
As a developer, I should be able to automatically manipulate data to test common, type-specific edge cases so that I can speed up my workflow and reduce human error.

### Sub-tasks
- [ ] Generate list of common edge cases for primitive data types (e.g. negative integers, empty strings, etc.)
- [ ] Generate list of common edge cases for composite data (e.g. empty arrays)
- [ ] Mock up UI for automatically applying suggested tests

## Notes
* This issue may depend on the ability to import saved test files
