### ISSUE TITLE
Send mutated data to destination micro-service

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#5]
## User story
As a developer, I should be able to send multiple data mockups to a pre-defined endpoint, so that I don’t need to make a separate HTTP request for each test scenario.

### Acceptance criteria
- [x] Should have the ability to send information as a request body
- [x] Should be able to edit the data and update the request body with the click of the request
- [x] Should be able to re-send information as many times as the developer needs to
- [x] Should be able to send a `PUT` method
- [x] Should be able to send a `PATCH` method

### Sub-tasks
- [x] Add ability to send mocked up data as request body to micro-service endpoint
- [x] Develop method to send request for each test case
- [x] Determine supported request methods (does it make sense to support methods outside of `PUT` and `POST`?
