### ISSUE TITLE
Display test passes/failures

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#7]
## User story
As a developer, I should be able to view basic responses for each test request so that I can find out how my micro-service responds to different data testing scenarios.

### Acceptance criteria
- [x] Should display UI response for either test passing/ failing
- [x] Should be able to see the changes highlighted
- [ ] ~Should allow for changes to be made without any refreshing or exiting of the tool~ (handled in mockup panel)

### Sub-tasks
- [x] Mock up UI for displaying micro-service responses
- [x] Ensure responses are associated with original requests

## Notes
* We ought to determine if users can define assertions (e.g. define expected results) and display a pass/fail report _or_ if we just want to display the response itself
⤷ Yes: see #52
* It’d be great to come up with a way to handle errors well—maybe some indication of severity, some sort of assertion structure… need to think more on this

**Comment by conor-jh** [comment]
There are some UI opportunities here, but original acceptance criteria are complete, so closing this one out.
