### ISSUE TITLE
Create and deploy basic download landing page

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#85]
Our app should have a basic landing page we can link to from ads, social promotions, etc. It’ll also be useful for résumés and online profiles. 

## Sub-tasks
- [x] Create basic, mobile-responsive design
- [x] Write webpage copy
- [x] Build “download” link that downloads packaged Electron app
